[server]
ip = "localhost"
port = "5000"

[app]
# Unidad en la que se busca la instalacion de PiQuatro
unidad = "C:"
# Hora del dia en la que se actualizara el servicio
update_time = 0
# Hora del dia en la que analiza por multiples instalaciones de PiQuatro
piquatro_time = 2
# Tiempo (en minutos) para enviar las etiquetas al servidor
intervalo_mins = 180


[auth]
clave_publica = "ABC123"
clave_privada = "QWERTY987"
clave_descarga = "ABC123"