@Server_HostAddress = http://rafatest.runfosa.local:8088/VST


POST {{Server_HostAddress}}/validarcliente
Content-Type: application/json
request-key: ABC123
request-hash: ZVh/7rh3ThlWjNQb0tZkvb3C4/5HBHqteNZ9kaXmYNk=

{
  "name": "192.168.10.25",
  "etiquetas": [
    {
      "hash": "ASVFWEHWHWE684765weggewegwegwgggwwWW",
      "name": "primaria_china"
    },
    {
      "hash": "ASVFWEHWHWE684765weggewegwegwgggwwWW",
      "name": "primaria_china1"
    },
    {
      "hash": "ASVFWEHWHWE684765weggewegwegwgggwwWW",
      "name": "primaria_china2"
    },
    {
      "hash": "ASVFWEHWHWE684765weggewegwegwgggwwWW",
      "name": "primaria_china3"
    }
  ]
}

###

GET {{Server_HostAddress}}/obtenercliente?key=abc